server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_HOST:http://proga.pw:8761/eureka}
  instance:
    preferIpAddress: true
management:
  security:
    enabled: ${actuator.protected:true}

spring.zipkin.baseUrl: http://GR-ZIPKIN/
spring:
  sleuth:
    sampler:
      percentage: 1